// <auto-generated />
using CarServices.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarServices.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220616060815_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarServices.Database.Entites.Car", b =>
                {
                    b.Property<string>("carid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("carbrand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("carname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cartype")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("carid");

                    b.ToTable("cars");
                });
#pragma warning restore 612, 618
        }
    }
}
